/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
//import org.free.chart.jFreeChart;
import org.jfree.chart.ChartPanel;






/**
 *
 * @author ALVARO JAVIER
 */
public class Interfaz_BombaPetroleo extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_BombaPetroleo
     */
    public Interfaz_BombaPetroleo() {
        
        
    
        initComponents();
        
        setSize(600,500);
        setResizable(false);
        setTitle("Bomba de Petroleo");
        setLocationRelativeTo(null);
        
        
        //ImageIcon Wallpaper= new ImageIcon("src/images/fondoenpaint.jpg");
        //Icon icono = new ImageIcon(Wallpaper.getImage().getScaledInstance( ))*//
                
                
        ImageIcon Wallpaper = new ImageIcon("src/imagenesopcional/fondoenpaint.jpg");
        Icon icono = new ImageIcon(Wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();
        
    }
    
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenesopcional/pump (1).png"));
        return retValue;
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_8 = new javax.swing.JTextField();
        jButton_GraficaMarcas = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese la diferencia de presión en pascales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 230, 70));

        jLabel2.setText("Ingrese el diametro de entrada en m");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, -1));

        jTextField_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, -1));

        jLabel3.setText("Ingrese el valor del caudal en m3/s");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTextField_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, -1));

        jLabel4.setText("Ingrese el diametro de salida en m");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jTextField_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, -1));

        jLabel5.setText(" Ingrese el consumo electrico en W");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jTextField_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 190, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("El Resultado es:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 260, 20));

        jTextField_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, -1));

        jLabel7.setText("Ingrese el valor de la eficiencia del motor actual:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jTextField_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 190, -1));

        jLabel8.setText("Ingrese el valor factor en correción");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 180, -1));

        jTextField_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 190, -1));

        jButton_GraficaMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesopcional/png.png"))); // NOI18N
        jButton_GraficaMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GraficaMarcasActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GraficaMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 120, 100));

        jLabel10.setText("Ingrese el valor de la densidad");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel11.setText("Presiones para calcular");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        jTextField_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 190, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 300, 180));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_1ActionPerformed

    private void jTextField_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_2ActionPerformed

    private void jTextField_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_3ActionPerformed

    private void jTextField_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_6ActionPerformed

    private void jTextField_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_4ActionPerformed

    private void jTextField_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_7ActionPerformed

    private void jTextField_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_8ActionPerformed

    private void jButton_GraficaMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GraficaMarcasActionPerformed
        



double num1, num2, num3, num4, num5, num6, num7, total, d1, d2, d3, d4, d5,d6, tubo, resultado, velocidad1, velocidad2, finala, diametro1, diametro2, i1,v1,v2;
double num8;

double gravedad = (float) 9.81;

num1 = Double.parseDouble(jTextField_1.getText());
num2 = Double.parseDouble(jTextField_2.getText());
 num3 = Double.parseDouble(jTextField_3.getText());
 num4 = Double.parseDouble(jTextField_4.getText());
 num5 = Double.parseDouble(jTextField_5.getText());
 num6 = Double.parseDouble(jTextField_6.getText());
 num7 = Double.parseDouble(jTextField_7.getText());
num8 = Double.parseDouble(jTextField_8.getText());

diametro1 = Math.pow(num2, 2);

velocidad1 = (num1) / ((3.1416 * diametro1) / 4);

 diametro2 = Math.pow(num3, 2);

 velocidad2 = (num1) / ((3.1416 * diametro2) / 4);

 d1 = num8 * ((Math.pow(velocidad2, 2)) - (Math.pow(velocidad1, 2)));
 d2 = (d1) / (2 * gravedad);
 d3 = (num6) / (num5 * gravedad);
 d4 = (d3 + d2);

 d5 = num5 * num1 * gravedad * d4;
 //d6=d5/1000;
 tubo = num7 * num4;
 resultado = d5 / tubo;
// finala = resultado;

total = resultado;
        System.out.println("d1");

 jTextField1.setText(String.valueOf(total+ "%"));

 
 
 
 
 DefaultCategoryDataset datos = new DefaultCategoryDataset();
    //datos.setValue(num2, total, "din");
   // datos.setValue(num3, total, "dino");
 
        org.jfree.chart.JFreeChart grafico_de_barras = ChartFactory.createBarChart3D(
         
         "diametros",
         "x",
         "y",
         datos,
         PlotOrientation.VERTICAL,
         true,
         true,
         false
         );
        
        ChartPanel panel = new ChartPanel(grafico_de_barras);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(300,180)); 
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel,BorderLayout.NORTH);
        
        pack();
        repaint();
        
 
 
 
 
 
 
 
 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton_GraficaMarcasActionPerformed

    private void jTextField_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_BombaPetroleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_BombaPetroleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_BombaPetroleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_BombaPetroleo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_BombaPetroleo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_GraficaMarcas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_1;
    private javax.swing.JTextField jTextField_2;
    private javax.swing.JTextField jTextField_3;
    private javax.swing.JTextField jTextField_4;
    private javax.swing.JTextField jTextField_5;
    private javax.swing.JTextField jTextField_6;
    private javax.swing.JTextField jTextField_7;
    private javax.swing.JTextField jTextField_8;
    // End of variables declaration//GEN-END:variables

    
}
